version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/pillpipe
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pillpipe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
