version: '3.8'
services:
  backend:
    build: ./server
    env_file: .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
